# Generated by Django 6.0.6 on 2026-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Permis (provisoire)'),
        ),
    ]
