# Generated by Django 6.0.7 on 2026-07-08 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidat_numero_permis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Examinateur',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='examencode',
            options={'ordering': ['-date_examen', '-id'], 'verbose_name': 'Examen code'},
        ),
        migrations.AlterModelOptions(
            name='examenconduite',
            options={'ordering': ['-date_examen', '-id'], 'verbose_name': 'Examen conduite'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='numero_cni',
        ),
        migrations.RemoveField(
            model_name='examenconduite',
            name='note',
        ),
        migrations.AddField(
            model_name='candidat',
            name='est_ancien_dossier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='examencode',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_code_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examenconduite',
            name='resultat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('REPROGRAMME', 'Reprogrammé'), ('ABSENT', 'Absent')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='examenconduite',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_conduite_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenconduite',
            name='examinateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='core.examinateur'),
        ),
    ]
