# Generated by Django 6.0.7 on 2026-07-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fiche', models.CharField(choices=[('fiche_controle', 'Fiche contrôle candidat'), ('fiche_examen_code', "Fiche d'examen code"), ('fiche_examen_conduite', "Fiche d'examen conduite"), ('attestation', 'Attestation provisoire')], max_length=30)),
                ('champ', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('x_mm', models.FloatField(default=20)),
                ('y_mm', models.FloatField(default=20)),
                ('taille_police', models.IntegerField(default=12)),
                ('largeur_mm', models.FloatField(blank=True, default=60, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position de champ imprimé',
                'verbose_name_plural': 'Positions des champs imprimés',
                'ordering': ['type_fiche', 'y_mm', 'x_mm'],
                'unique_together': {('type_fiche', 'champ')},
            },
        ),
    ]
