# Generated by Django 6.0.6 on 2026-06-09 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auto-école',
                'verbose_name_plural': 'Auto-écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('numero_cni', models.CharField(blank=True, max_length=50, verbose_name='N° CNI')),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('categorie', models.CharField(choices=[('A1', 'A1'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('auto_ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='core.autoecole')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidat',
                'ordering': ['-date_inscription', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ExamenCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField()),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resultat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('ABSENT', 'Absent')], default='EN_ATTENTE', max_length=15)),
                ('date_saisie', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_code', to='core.candidat')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen code',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='ExamenConduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField()),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resultat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('ABSENT', 'Absent')], default='EN_ATTENTE', max_length=15)),
                ('date_saisie', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_conduite', to='core.candidat')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen conduite',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('SAISIE_RESULTAT', 'Saisie résultat')], max_length=20)),
                ('modele', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Agent Direction')], default='direction', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
