# Generated by Django 6.0.7 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examinateur_alter_examencode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de permis',
                'verbose_name_plural': 'Catégories de permis',
                'ordering': ['ordre', 'code'],
            },
        ),
    ]
